# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
    ]
