# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_show_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(),
        ),
    ]
